# Generated by Django 5.2 on 2025-05-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoJB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_abertura', models.TimeField()),
                ('horario_fechamento', models.TimeField()),
                ('dia_semana', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Configuração de horário',
                'verbose_name_plural': 'Configurações de horário',
            },
        ),
    ]
