# Generated by Django 5.2 on 2025-06-17 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaojb',
            options={'verbose_name': 'Configuração de Horário de Funcionamento do Jardim Botânico', 'verbose_name_plural': 'Configurações de Horário de Funcionamento do Jardim Botânico'},
        ),
    ]
