# Generated by Django 5.2 on 2025-05-05 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amostras', '0002_amostra_descricao_acessivel'),
        ('trilhas', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amostra',
            name='localizacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trilhas.ponto'),
        ),
    ]
