# Generated by Django 5.2 on 2025-05-14 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitante', models.CharField(max_length=255)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.agendamento')),
            ],
        ),
    ]
