# Generated by Django 5.2 on 2025-06-17 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presenca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presenca',
            options={'verbose_name': 'Presença no Agendamento do Jardim Botânico', 'verbose_name_plural': 'Presenças no Agendamento do Jardim Botânico'},
        ),
    ]
