# Generated by Django 5.2 on 2025-04-29 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosCientificos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cientifico', models.CharField(blank=True, max_length=255, null=True)),
                ('reino', models.CharField(blank=True, max_length=255, null=True)),
                ('filo', models.CharField(blank=True, max_length=255, null=True)),
                ('classe', models.CharField(blank=True, max_length=255, null=True)),
                ('ordem', models.CharField(blank=True, max_length=255, null=True)),
                ('familia', models.CharField(blank=True, max_length=255, null=True)),
                ('genero', models.CharField(blank=True, max_length=255, null=True)),
                ('especie', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Amostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cientifico', models.CharField(max_length=255)),
                ('nome_popular', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('planta', 'Planta'), ('fungo', 'Fungo'), ('animal', 'Animal')], default='planta', max_length=10)),
                ('origem', models.CharField(blank=True, max_length=255, null=True)),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='amostras/')),
                ('imagem_url', models.CharField(blank=True, max_length=300, null=True)),
                ('dados_cientificos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trilhas.dadoscientificos')),
            ],
        ),
    ]
