# Generated by Django 5.2 on 2025-05-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trilhas', '0002_delete_amostra_delete_dadoscientificos'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaTrilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Guias de Trilhas',
            },
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pontos',
            },
        ),
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('guias', models.ManyToManyField(to='trilhas.guiatrilha')),
                ('pontos', models.ManyToManyField(to='trilhas.ponto')),
            ],
            options={
                'verbose_name_plural': 'Trilhas',
            },
        ),
    ]
