# Generated by Django 5.2 on 2025-05-05 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('trilhas', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trilha',
            name='guias',
        ),
        migrations.AddField(
            model_name='ponto',
            name='guia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trilhas.guiatrilha'),
        ),
        migrations.AddField(
            model_name='ponto',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trilha',
            name='tags',
            field=models.ManyToManyField(to='tag.tag'),
        ),
    ]
