# Generated by Django 5.2 on 2025-05-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0004_remove_trilha_guias_ponto_guia_ponto_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilha',
            name='dificuldade',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trilha',
            name='duracao',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
