# Generated by Django 5.2 on 2025-05-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0005_trilha_dificuldade_trilha_duracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trilha',
            name='duracao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
