# Generated by Django 5.2 on 2025-05-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0006_alter_trilha_duracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='trilhas/'),
        ),
    ]
