# Generated by Django 5.2 on 2025-05-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0007_ponto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiatrilha',
            name='proximo_passo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
