# Generated by Django 5.2 on 2025-06-17 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0008_guiatrilha_proximo_passo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guiatrilha',
            options={'verbose_name': 'Guia de Trilha do Jardim Botânico', 'verbose_name_plural': 'Guias de Trilhas do Jardim Botânico'},
        ),
        migrations.AlterModelOptions(
            name='ponto',
            options={'verbose_name': 'Ponto da Trilha do Jardim Botânico', 'verbose_name_plural': 'Pontos da Trilha do Jardim Botânico'},
        ),
        migrations.AlterModelOptions(
            name='trilha',
            options={'verbose_name': 'Trilha Guiada do Jardim Botânico', 'verbose_name_plural': 'Trilhas Guiadas do Jardim Botânico'},
        ),
        migrations.AlterField(
            model_name='ponto',
            name='guia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trilhas.guiatrilha'),
        ),
    ]
