# Generated by Django 5.2 on 2025-06-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0009_alter_guiatrilha_options_alter_ponto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trilha',
            name='duracao',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
