# Generated by Django 5.2 on 2025-06-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0010_alter_trilha_duracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trilha',
            name='dificuldade',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Fácil'), (2, 'Médio'), (3, 'Difícil')], null=True),
        ),
    ]
