# Generated by Django 5.2 on 2025-05-14 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('matricula', models.CharField(max_length=25, unique=True)),
                ('curso', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioBolsista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField()),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('bolsista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolsista.bolsista')),
            ],
        ),
    ]
