# Generated by Django 5.2 on 2025-06-17 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolsista', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bolsista',
            options={'verbose_name': 'Bolsista do Jardim Botânico', 'verbose_name_plural': 'Bolsistas do Jardim Botânico'},
        ),
        migrations.AlterModelOptions(
            name='horariobolsista',
            options={'verbose_name': 'Horário do Bolsista do Jardim Botânico', 'verbose_name_plural': 'Horários do Bolsista do Jardim Botânico'},
        ),
    ]
