# Generated by Django 5.2 on 2025-06-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsista', '0002_alter_bolsista_options_alter_horariobolsista_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariobolsista',
            name='dia_semana',
            field=models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')]),
        ),
    ]
