# Generated by Django 5.2 on 2025-05-16 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amostras', '0003_amostra_localizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAmostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=255)),
                ('resposta_correta', models.CharField(max_length=255)),
                ('resposta_incorreta_1', models.CharField(max_length=255)),
                ('resposta_incorreta_2', models.CharField(max_length=255)),
                ('amostra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostras.amostra')),
            ],
        ),
    ]
