# Generated by Django 5.2 on 2025-06-17 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizamostra',
            options={'verbose_name': 'Pergunta do Quiz do Jardim Botânico', 'verbose_name_plural': 'Perguntas do Quiz do Jardim Botânico'},
        ),
    ]
