# Generated by Django 5.2 on 2025-05-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('nome_escola_instituto', models.CharField(max_length=255)),
                ('nome_responsavel', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('endereco_escola_instituto', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_institituicao', models.CharField(choices=[('publica_municipal', 'Pública Municipal'), ('publica_estadual', 'Pública Estadual'), ('publica_federal', 'Pública Federal'), ('privada', 'Privada'), ('filantropica', 'Filantropica'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('nivel_instituicao', models.CharField(choices=[('infantil', 'Educação Infantil'), ('fundamental_inicial', 'Educação Fundamental - Séries Iniciais'), ('fundamental_final', 'Educação Fundamental - Séries Finais'), ('medio', 'Ensino Médio'), ('superior', 'Ensino Superior'), ('nao_escolar', 'Não escolar')], default='nao_escolar', max_length=55)),
                ('ano_serie_semestre_turma', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_previsto_visitantes', models.CharField(blank=True, max_length=255, null=True)),
                ('data_agendamento', models.DateField()),
                ('tempo_disponivel', models.TimeField()),
                ('horario_pretendido', models.TimeField()),
                ('necessaria_adaptacao', models.BooleanField(default=False)),
                ('adaptacao_descricao', models.TextField(blank=True, null=True)),
                ('primeira_atividade', models.CharField(choices=[('caminhada_guiada', 'Caminhada guiada pelo Jardim Botânico (1h30-2h) - todas as idades'), ('telhado_verde', 'Telhado verde e agenda 2030 (até 40 min) - a partir de 9 anos'), ('jardim_sensorial', 'Jardim Sensorial (até 30 min) - todas as idades'), ('exposicao_taxidermia', 'Exposição de animais taxidermizados - todas as idades'), ('palestra_peconhentos', 'Palestra sobre prevenção de acidentes com animais peçonhentos - a partir de 9 anos'), ('chapeuzinho_verde', '“Chapeuzinho Verde e o Jardim Encantado” (pré ao 2º ano)'), ('horta_mandala', 'Visita à horta mandala do Jardim Botânico - horta sustentável (terças de manhã)'), ('artesanato_botanico', 'Artesanato botânico (terças de manhã e quartas à tarde)'), ('culinaria_pancs', 'Culinária com PANCS (terças de manhã e quartas à tarde)')], max_length=255)),
                ('segunda_atividade', models.CharField(choices=[('caminhada_guiada', 'Caminhada guiada pelo Jardim Botânico (1h30-2h) - a partir de 9 anos'), ('telhado_verde', 'Telhado verde e agenda 2030 (até 40 min) - a partir de 9 anos'), ('jardim_sensorial', 'Jardim Sensorial (até 30 min) - todas as idades'), ('exposicao_taxidermia', 'Exposição de animais taxidermizados - todas as idades'), ('palestra_peconhentos', 'Palestra sobre prevenção de acidentes com animais peçonhentos - a partir de 9 anos')], max_length=255)),
                ('aliar_conteudo_escolar', models.BooleanField(default=False)),
                ('conteudo_escolar', models.TextField(blank=True, null=True)),
                ('piquenique', models.BooleanField(default=False)),
            ],
        ),
    ]
