# Generated by Django 5.2 on 2025-06-17 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'verbose_name': 'Agendamento do Jardim Botânico', 'verbose_name_plural': 'Agendamentos do Jardim Botânico'},
        ),
    ]
