# Generated by Django 5.2 on 2025-06-17 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag das Trilhas e Amostras do Jardim Botânico', 'verbose_name_plural': 'Tags das Trilhas e Amostras do Jardim Botânico'},
        ),
    ]
